name: Docs Deploy

on:
  push:
    branches: [ master ]
    paths:
      - "xkDocs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Docs
        working-directory: .
        run: |
          npm ci
          npm run docs:build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy dist to server
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            xkDocs/.vitepress/dist/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DOCS_PATH }}

      - name: Reload Nginx
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "sudo systemctl reload nginx"
